# Eciton - experimental exokernel.
# Copyright (C) 2025 Alexander (@alkuzin).
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <https://www.gnu.org/licenses/>.

# Crate unstable features section.
[unstable]
# Feature that provides memory-related built-in functions.
build-std-features = ["compiler-builtins-mem"]
# Components of the standard library to build.
# "core" - is the minimal subset of the Rust standard library,
# suitable for no_std environments.
# "compiler_builtins" - low-level built-in functions.
build-std = ["core", "compiler_builtins"]

# Build process configuration section.
[build]
# Target configuration file for the build process.
target = "targets/i686/i686-unknown-none.json"