# SPDX-License-Identifier: GPL-3.0-or-later
# Date: 2025-06-13
# Author: Alexander Kuzin <alkuzindev@gmail.com>.

# Crate unstable features section.
[unstable]

# Feature that provides memory-related built-in functions.
build-std-features = ["compiler-builtins-mem"]

# Components of the standard library to build.
# "core" - is the minimal subset of the Rust standard library,
# suitable for no_std environments.
# "compiler_builtins" - low-level built-in functions.
build-std = ["core", "compiler_builtins"]

# Build process configuration section.
[build]
# Target configuration file for the build process.
target = "targets/x86/x86-unknown-none.json"